version: '3.9'

services:
  db:
    image: postgres:15
    container_name: superhero_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build: .
    container_name: superhero_api
    ports:
      - "8000:8000"
    depends_on:
      - db
